number: 'None'
symbol: 'None'
lang_char: '/mnt/122a7683-fa4b-45dd-9f13-b18cc4f4a187/github_repos/ocr-as-retrieval/full_charset_jp.txt'
experiment_name: 'pr_005050_init'
train_data: 'easyocr_data/pr_005050_train'
valid_data: 'easyocr_data/pr_005050_val'
test_data: 'easyocr_data/pr_005050_test'
manualSeed: 1111
workers: 6
batch_size: 64 #32
num_iter: 30000 # 300000
valInterval: 2000 # 20000
saved_model: './japanese_g2.pth'
FT: True
optim: False # default is Adadelta
lr: 1.
beta1: 0.9
rho: 0.95
eps: 0.00000001
grad_clip: 5
#Data processing
select_data: 'pr_005050_train' # this is dataset folder in train_data
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 64 
imgH: 64
imgW: 600
rgb: False
contrast_adjust: False
sensitive: True
PAD: True
contrast_adjust: 0.0
data_filtering_off: True
vertical: False
# Model Architecture
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: True
freeze_FeatureFxtraction: True
freeze_SequenceModeling: True